/**
 * Generates `supabase/seed/seed.sql` from the workbook-extracted JSON
 * (distance_matrix.json, weekly_fuel.json) plus the default rate card.
 *
 * Run: `npm run seed:gen`  then apply seed.sql to the database.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DEFAULT_BASE_RATES, DEFAULT_FIDIC, ORIGINS } from '../../shared/rates';

const here = dirname(fileURLToPath(import.meta.url));
const q = (s: string | null) => (s == null ? 'null' : `'${s.replace(/'/g, "''")}'`);

interface DistRow {
  region: string | null;
  district: string;
  capital: string | null;
  km: Record<string, number | null>;
}
const districts = JSON.parse(readFileSync(join(here, 'distance_matrix.json'), 'utf8')) as DistRow[];
const fuel = JSON.parse(readFileSync(join(here, 'weekly_fuel.json'), 'utf8')) as {
  week_start: string;
  price: number;
}[];

const out: string[] = [];
out.push('-- AUTO-GENERATED by generate_seed.ts — do not edit by hand.');
out.push('begin;');

// Origins
out.push('\n-- origins');
ORIGINS.forEach((name, i) =>
  out.push(`insert into origins (id, name) values (${i + 1}, ${q(name)}) on conflict (id) do nothing;`),
);

// Districts
out.push('\n-- districts');
for (const d of districts) {
  out.push(
    `insert into districts (name, capital, region) values (${q(d.district)}, ${q(d.capital)}, ${q(
      d.region,
    )}) on conflict (name) do nothing;`,
  );
}

// Distance matrix
out.push('\n-- distance_matrix');
for (const d of districts) {
  ORIGINS.forEach((origin, i) => {
    const km = d.km[origin];
    if (km == null) return;
    out.push(
      `insert into distance_matrix (origin_id, district_id, km) ` +
        `select ${i + 1}, id, ${km} from districts where name = ${q(d.district)} ` +
        `on conflict (origin_id, district_id) do update set km = excluded.km;`,
    );
  });
}

// Rate version + FIDIC + base rates
out.push('\n-- rate version (2022 FIDIC baseline)');
out.push(`insert into rate_versions (id, label, effective_from, is_active)
  values ('00000000-0000-0000-0000-000000000001', '2022 FIDIC baseline', '2022-10-01', true)
  on conflict (id) do nothing;`);
const f = DEFAULT_FIDIC;
out.push(`insert into fidic_params (rate_version_id, a, b, c, w_old, w_new, f_old)
  values ('00000000-0000-0000-0000-000000000001', ${f.a}, ${f.b}, ${f.c}, ${f.Wo}, ${f.Wn}, ${f.Fo})
  on conflict do nothing;`);
out.push('\n-- base rates');
for (const [key, val] of Object.entries(DEFAULT_BASE_RATES)) {
  out.push(
    `insert into rates (rate_version_id, item_key, base_rate) ` +
      `values ('00000000-0000-0000-0000-000000000001', ${q(key)}, ${val}) ` +
      `on conflict (rate_version_id, item_key) do update set base_rate = excluded.base_rate;`,
  );
}

// Weekly fuel
out.push('\n-- weekly_fuel (historical series from workbook)');
for (const w of fuel) {
  out.push(
    `insert into weekly_fuel (week_start, price_per_litre, status) ` +
      `values ('${w.week_start}', ${w.price}, 'manual') ` +
      `on conflict (week_start) do update set price_per_litre = excluded.price_per_litre;`,
  );
}

out.push('\ncommit;');
const target = join(here, 'seed.sql');
writeFileSync(target, out.join('\n') + '\n');
console.log(`Wrote ${target} (${districts.length} districts, ${fuel.length} fuel weeks)`);
